baseurl = "/"
languageCode = "en-us"
title = "x-camp"
copyright = "Copyright (c) 2008 - 2017, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-bootstrap"
publishDir = "public"
contentdir = "content"
disqusShortname = "xxxxxx"
googleAnalytics = "UA-XXXXXXX-1"

[[menu.main]]
    name = "RULES"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "rules"
    url = "/page/rules"

[[menu.main]]
    name = "TAGS"
    pre = "<i class='fa fa-tags'></i>"
    weight = -110
    identifier = "tags"
    url = "/tags/"

[[menu.main]]
    name = "CATEGORIES"
    pre = "<i class='fa fa-folder-open'></i>"
    weight = -100
    identifier = "categories"
    url = "/categories/"

[[menu.main]]

    name = "ABOUT ME"
    pre = "<i class='fa fa-info-circle'></i>"
    weight = -90
    identifier = "about-me"
    url = "/page/about-me"


[params.widgets]
  recent_articles = true
  categories = true
  tags = true
  tag_cloud = false


[params.banner]
  img src = "/logo.png"
